export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_IS_LOGIN = "SET_IS_LOGIN";
export const SET_ONLINE_USERS = "SET_ONLINE_USERS";
export const SET_STREAMS = "SET_STREAMS";
export const SET_SIDEBAR_COLLAPSED = "SET_SIDEBAR_COLLAPSED";
